[analysis]
ifos=['H1','L1','V1']
singularity=False
osg=False

[condor]
accounting_group=ligo.sim.o4.cbc.pe.rift
accounting_group_user=aasim.jan

[datafind]
url-type = file
types = {'H1': 'O4MDC', 'L1': 'O4MDC', 'V1': 'O4MDC'}

[data]
channels = {'H1': 'H1:FAKE-STRAIN', 'L1': 'L1:FAKE-STRAIN', 'V1': 'V1:FAKE-STRAIN'}

[lalinference]
flow = {'H1': 20.0, 'L1': 20.0, 'V1': 20.0}
fhigh = {'H1': 1024.0, 'L1': 1024.0, 'V1': 1024.0}

[engine]
# Approximant
fref=15

# Distance 
distance-max = 750

# Data 
seglen = 4
srate = 2048

[rift-pseudo-pipe]
# ILE
internal-ile-use-lnL=True
internal-ile-request-disk="8M"
internal-ile-request-memory="8192"
ile-runtime-max-minutes=700
ile-jobs-per-worker=18
ile-n-eff=20
ile-sampler-method="AV"
ile-copies=1
ile-no-gpu=True
ile-retires=3

# Extrinsic ILE
internal-last-iteration-extrinsic-samples-per-ile=20
add-extrinsic=True
batch-extrinsic=True
add-extrinsic-time-resampling=True

# CIP
internal-cip-use-lnL=True
cip-fit-method="rf"
cip-sampler-method="AV"
cip-explode-jobs=5
cip-explode-jobs-last=2
n-output-samples=5000
n-output-samples-last=5000
cip-sigma-cut=0.4
force-mc-range=[20, 25]
force-eta-range=[0.05,0.22]

# Approximant
approx="NRHybSur2dq15"
l-max=4
fmin-template=15
use-gwsurrogate=True

# Algorithm
internal-test-convergence-threshold=0.001
internal-flat-stratergy=True
internal-force-iterations=4
internal-force-puff-iterations=3
internal-loud-signal-mitigation-suite=True
internal-n-evaluations-per-iteration=5000
#only-primary-spinning=True
#force-chi-max=0.99
assume-nospin=True

# OSG
use_osg=False
use_osg_file_transfer=False
use_osg_cip=False

